CC = gcc
CFLAGS = -Wall -Wextra -std=c99

all: exercice1 exercice2 exercice3 exercice4 exercice5 exercice6

exercice1: exercice1.c
	$(CC) $(CFLAGS) exercice1.c -o exercice1

exercice2: exercice2.c
	$(CC) $(CFLAGS) exercice2.c -o exercice2

exercice3: exercice3.c
	$(CC) $(CFLAGS) exercice3.c -o exercice3

exercice4: exercice4.c
	$(CC) $(CFLAGS) exercice4.c -o exercice4

etudiant: exercice5.c
	$(CC) $(CFLAGS) exercice5.c -o exercice5

exercice6: exercice6.c
	$(CC) $(CFLAGS) exercice6.c -o exercice6

clean:
	rm -f exercice1 exercice2 exercice3 exercice4 exercice5 exercice6

.PHONY: all clean
